spec:
  name: messagequest-server
  region: nyc
  services:
  - name: supabase
    dockerfile_path: Dockerfile.digitalocean
    source_dir: /
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
    - key: POSTGRES_DB
      value: messagequest
      type: SECRET
    - key: POSTGRES_USER
      value: postgres
      type: SECRET
    - key: POSTGRES_PASSWORD
      type: SECRET
    - key: JWT_SECRET
      type: SECRET
    - key: ANON_KEY
      type: SECRET
    - key: SERVICE_ROLE_KEY
      type: SECRET
    - key: SUPABASE_URL
      value: "https://${APP_DOMAIN}"
    - key: APNS_KEY_ID
      type: SECRET
    - key: APNS_TEAM_ID
      type: SECRET
    - key: APNS_BUNDLE_ID
      value: "com.messagequest.app"
    - key: APNS_PRIVATE_KEY
      type: SECRET
    - key: OPENAI_API_KEY
      type: SECRET
    http_port: 8080
    routes:
    - path: /
  databases:
  - name: messagequest-db
    engine: PG
    version: "14"
    size: db-s-dev-database
    num_nodes: 1